version: "2"
services:
    serverless-tutorial:
      build: ./
      image: serverless-tutorial:latest
      container_name: serverless-tutorial
      env_file: ./.env
      volumes:
        - /var/lib/serverless-tutorial
        - /var/lib/serverless-tutorial/node_modules
